Management.Web/Management.Web/Models/ErrorViewModel.cs
namespace Management.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Management.Web/Management.Web/Models/LeaveTypeVM.cs
using System.ComponentModel.DataAnnotations;

namespace Management.Web.Models
{
    public class LeaveTypeVM
    {
        public int Id { get; set; }
        [Display(Name = "Leave Type Name")]
        [Required]
        public string Name { get; set; }
        [Display(Name = "Default Number Of Days")]
        [Required]
        [Range(1, 25, ErrorMessage = "Please Enter A Valid Number")]
        public int DefaultDays { get; set; }
    }
}

Management.Web/Management.Web/Controllers/HomeController.cs
using Management.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Management.Web.Controllers
{
    // eg: Home/Index
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Management.Web/Management.Web/Controllers/LeaveTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Management.Web.Data;
using AutoMapper;
using Management.Web.Models;
using Management.Web.Contracts;

namespace Management.Web.Controllers
{
    public class LeaveTypesController : Controller
    {
        private readonly ILeaveTypeRepository leaveTypeRepository;
        private readonly IMapper mapper;

        public LeaveTypesController(ILeaveTypeRepository leaveTypeRepository, IMapper mapper)
        {
            this.leaveTypeRepository = leaveTypeRepository;
            this.mapper = mapper;
        }

        // GET: LeaveTypes
        public async Task<IActionResult> Index()
        {
           var leaveTypes = mapper.Map<List<LeaveTypeVM>>(await leaveTypeRepository.GetAllAsync()); 
           return View(leaveTypes);
        }

        // GET: LeaveTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var leaveType = await leaveTypeRepository.GetAsync(id);
            if (leaveType == null)
            {
                return NotFound();
            }

            var leaveTypeVM = mapper.Map<LeaveTypeVM>(leaveType);
            return View(leaveTypeVM);
        }

        // GET: LeaveTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LeaveTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LeaveTypeVM leaveTypeVM)
        {
            if (ModelState.IsValid)
            {
                var leaveType = mapper.Map<LeaveType>(leaveTypeVM);
                leaveTypeRepository.AddAsync(leaveType);
                return RedirectToAction(nameof(Index));
            }
            return View(leaveTypeVM);
        }

        // GET: LeaveTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var leaveType = await leaveTypeRepository.GetAsync(id);
            if (leaveType == null)
            {
                return NotFound();
            }
            var leaveTypeVM = mapper.Map<LeaveTypeVM>(leaveType);
            return View(leaveTypeVM);
        }

        // POST: LeaveTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, LeaveTypeVM leaveTypeVM)
        {
            if (id != leaveTypeVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var leaveType= mapper.Map<LeaveType>(leaveTypeVM);
                    await leaveTypeRepository.UpdateAsync(leaveType);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await leaveTypeRepository.Exists(leaveTypeVM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(leaveTypeVM);
        }

        // POST: LeaveTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            leaveTypeRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Management.Web/Management.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Management.Web/Management.Web/Views/LeaveTypes/Create.cshtml
@model LeaveTypeVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create Leave Type</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="DefaultDays" class="control-label"></label>
                <input asp-for="DefaultDays" class="form-control" />
                <span asp-validation-for="DefaultDays" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <a asp-action ="Index" class="btn btn-dark">Back to List</a> &nbsp;
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
</div>

Management.Web/Management.Web/Views/LeaveTypes/Delete.cshtml
@model Management.Web.Data.LeaveType

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LeaveType</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DefaultDays)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DefaultDays)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateModified)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Management.Web/Management.Web/Views/LeaveTypes/Details.cshtml
@model LeaveTypeVM;

@{
    ViewData["Title"] = "Details";
}

<h1>Details of @Model.Name</h1>

<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-5">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-7">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-5">
            @Html.DisplayNameFor(model => model.DefaultDays)
        </dt>
        <dd class = "col-sm-7">
            @Html.DisplayFor(model => model.DefaultDays)
        </dd>
    </dl>
</div>
<br/>
<div>
    <a asp-action="Index" class="btn btn-dark">Back to List</a>
    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model?.Id">Edit</a> 
</div>

Management.Web/Management.Web/Views/LeaveTypes/Edit.cshtml
@model LeaveTypeVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit LeaveType</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="DefaultDays" class="control-label"></label>
                <input asp-for="DefaultDays" class="form-control" />
                <span asp-validation-for="DefaultDays" class="text-danger"></span>
            </div>
             <input type="hidden" asp-for="Id" />
            <br/>
            <div class="form-group">
                <a asp-action ="Index" class="btn btn-dark">Back to List</a> &nbsp;
                <input type="submit" value="Save Changes" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

Management.Web/Management.Web/Views/LeaveTypes/Index.cshtml
@model IEnumerable<LeaveTypeVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a class="btn btn-success" asp-action="Create"><i class="fa-solid fa-plus"></i> Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DefaultDays)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DefaultDays)
            </td>
            <td>
                <a class="btn btn-warning" asp-route-id="@item.Id"><i class="fas fa-pencil-alt"></i></a> 
                <a class="btn btn-info" asp-route-id="@item.Id"><i class="fa-solid fa-circle-info"></i></a> 
@*                <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Delete</a *@ 
               <button data-id="@item.Id" class = "btn btn-danger deleteBtn" type="button"><i class="fa-solid fa-trash-can"></i></button>
                
            </td>
        </tr>
}
    </tbody>
</table>

<form id="deleteFrom" asp-action="Delete">
    <input type="hidden" id="leaveTypeId" name="Id" />
</form>

@section Scripts {
    <script>
        $(function(){

            $('.table').DataTable();

            $('.deleteBtn').click(function(e){
                swal({
                    title: "Are you sure?",
                    text: "Are you sure you want to delete this record?",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true
                }).then((confirm) => {
                    if(confirm){
                        var btn = $(this);
                        var id = btn.data("id");
                        $('#leaveTypeId').val(id);
                        $('#deleteFrom').submit();
                    }
                });
            });
        });
    </script>
}

Management.Web/Management.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Management.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css" />
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" asp-append-version="true" /> 
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Management.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Leave Management.Web - NET 6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between container">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Apply For Leave</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">My Leave</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Management</a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" asp-controller="LeaveTypes" asp-action="Index">Leave Types</a></li>
                              <li><a class="dropdown-item" href="#">Leave Allocations</a></li>
                              <li><a class="dropdown-item" href="#">Leave Requests</a></li>
                              <li><a class="dropdown-item" href="#">Employee Management</a></li>
                            </ul>
                      </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Management.Web - NET 6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"><script>

></script>
    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>